name: spa_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animate_do: ^3.3.4
  card_swiper: ^3.0.1
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.3.0

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
